#!/bin/bash

# This script installs dynamodb local if it doesn't exist and starts the server

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $THIS_DIR/common
cp scripts/dynamodb/serverless.yml ./
serverless dynamodb install
serverless dynamodb start

